d = {
          "WAS":"Washington Wizards",
          "CHA": "Charlotte Hornets",
          "ATL": "Atlanta Hawks",
          "MIA": "Miami Heat",
          "ORL": "Orlando Magic",
          "NY":"New York Knicks",
          "PHI":"Philadelphia 76ers",
          "BKN":"Brooklyn Nets",
          "BOS": "Boston Celtics",
          "TOR": "Toronto Raptors",
          "CHI": "Chicago Bulls",
          "CLE":"Cleveland Cavaliers",
          "IND":"Indiana Pacers",
          "DET":"Detroit Pistons",
          "MIL":"Milwaukee Bucks",
          "MIN":"Minnesota Timberwolves",
          "UTA":"Utah Jazz",
          "OKC":"Oklahoma City Thunder",
          "POR":"Portland Trail Blazers",
          "DEN":"Denver Nuggets",
          "MEM":"Memphis Grizzlies",
          "HOU":"Houston Rockets",
          "NO":"New Orleans Pelicans",
          "SA":"San Antonio Spurs",
          "DAL":"Dallas Mavericks",
          "GS":"Golden State Warriors",
          "LAL":"Los Angeles Lakers",
          "LAC":"Los Angeles Clippers",
          "PHO":"Phoenix Suns",
          "SAC":"Sacramento Kings",
}
